### ISSUE TITLE
Effect Speed LED

### ISSUE THREAD

**Issue by moskyow** [dave-code-ruiz/elkbledom#46]
I have paired my two strip led and ON/OFF command works.
The integration have found Effect Speed LED, but nothig happens if I change that value (0-100 range).
The integration did not founf the RGB settings.

**Comment by dave-code-ruiz** [comment]
Use debug log to see more information of posible errors.

In configuration.yaml:

```
logger:
  default: info
  logs:
    custom_components.elkbledom: debug
```

Post log results.
