### ISSUE TITLE
Set Color

### ISSUE THREAD

**Issue by namornoditz** [dave-code-ruiz/elkbledom#48]
Thx for your integration. Works fine.
Is there a option to set the color via scripts using yaml code? 
I've tried the RGB, RGBW, etc. options form the light domain, but this does not work for me.
br

**Comment by namornoditz** [comment]
It works now. Maybe you wanna add such an example to the info.

```
show_name: true
show_icon: true
name: Red
type: button
tap_action:
  action: call-service
  service: light.turn_on
  target:
    entity_id: light.test
  data:
    rgb_color:
      - 255
      - 0
      - 0
    brightness: 255
```
